### ISSUE TITLE
save error with arabic chars in translated title

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1116]
testing on gh-1081 branch locally.

If I enter arabic characters in the title field, I get an error saving subtitles and see this in the output log.

```
[13/Dec/2013 07:54:03] "GET /en/site_media/images/subtitle-editor/glyphicons_358_file_import.png HTTP/1.1" 200 600
ERROR 2013-12-13 07:54:04,621 api.base Failure on api
Traceback (most recent call last):
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/tastypie/resources.py", line 192, in wrapper
    response = callback(request, *args, **kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/tastypie/resources.py", line 406, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/tastypie/resources.py", line 427, in dispatch
    response = method(request, **kwargs)
  File "/opt/apps/unisubs/unisubs-integration/apiv2/api.py", line 1133, in post_detail
    return self.put_detail(request, **kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/tastypie/resources.py", line 1131, in put_detail
    updated_bundle = self.obj_update(bundle, request=request, **self.remove_api_resource_names(kwargs))
  File "/opt/apps/unisubs/unisubs-integration/apiv2/api.py", line 967, in obj_update
    return self.obj_create(bundle, request, **kwargs)
  File "/opt/apps/unisubs/unisubs-integration/apiv2/api.py", line 957, in obj_create
    version = form.save()
  File "/opt/apps/unisubs/unisubs-integration/apiv2/forms.py", line 171, in save
    metadata=data.get('metadata'))
  File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 555, in add_subtitles
    metadata)
  File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 402, in _add_subtitles
    version = sl.add_version(subtitles=subtitles, **data)
  File "/opt/apps/unisubs/apps/subtitles/models.py", line 775, in add_version
    sv.save()
  File "/opt/apps/unisubs/apps/subtitles/models.py", line 1459, in save
    return super(SubtitleVersion, self).save(*args, **kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/opt/apps/unisubs/middleware.py", line 168, in execute
    return super(MetricsCursorWrapper, self).execute(query, params)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 203, in execute
    if not self._defer_warnings: self._warning_check()
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Incorrect string value: '\xD9\x81\xD8\xB1\xD9\x8A...' for column 'title' at row 1
[13/Dec/2013 07:54:04] "POST /api2/partners/videos/e3zxQTG813na/languages/ar/subtitles/ HTTP/1.1" 500 3654
[13/Dec/2013 07:54:11] "POST /ar/subtitles/editor/e3zxQTG813na/ar/regain/ HTTP/1.1" 200 12
```

**Comment by PCF-Testing** [comment]
Old ticket, not a problem anymore.
