### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_authenticated'

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1186]
I got this error when testing against staging branch locally.

I'm was logged in as a team contributor and trying to complete a transcribe task via the old editor.

I couldn't reproduce when doing the same action via the new editor, nor when I tried again via the old editor.

```
[20/Jan/2014 05:22:31] "GET /en/site_media/images/arrows.gif HTTP/1.1" 200 114
[20/Jan/2014 05:22:39] "GET /en/site_media/images/check-sprite.gif HTTP/1.1" 200 75
ERROR 2014-01-20 05:22:43,307 django.request Internal Server Error: /widget/rpc/xhr/finished_subtitles
Traceback (most recent call last):
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/apps/unisubs/apps/widget/views.py", line 392, in rpc
    result = func(**args)
  File "/opt/apps/unisubs/apps/widget/rpc.py", line 834, in finished_subtitles
    task_approved, task_type, save_for_later)
  File "/opt/apps/unisubs/apps/widget/rpc.py", line 801, in save_finished
    task_id, task_type, task_notes, task_approved)
  File "/opt/apps/unisubs/apps/widget/rpc.py", line 611, in _save_tasks_for_save
    task.complete()
  File "/opt/apps/unisubs/apps/teams/models.py", line 1911, in complete
    }[Task.TYPE_NAMES[self.type]]()
  File "/opt/apps/unisubs/apps/teams/models.py", line 1974, in _complete_subtitle
    if self.workflow.requires_review_or_approval and not self._can_publish_directly(sv):
  File "/opt/apps/unisubs/apps/teams/models.py", line 1925, in _can_publish_directly
    self.language) and
  File "/opt/apps/unisubs/apps/teams/permissions.py", line 598, in can_publish_edits_immediately
    return can_approve(team_video, user, lang)
  File "/opt/apps/unisubs/apps/teams/permissions.py", line 534, in can_approve
    role = get_role_for_target(user, team_video.team, team_video.project, lang)
  File "/opt/apps/unisubs/apps/teams/permissions.py", line 97, in get_role_for_target
    member = get_member(user, team)
  File "/opt/apps/unisubs/apps/teams/permissions.py", line 78, in get_member
    return team.get_member(user)
  File "/opt/apps/unisubs/apps/teams/models.py", line 341, in get_member
    if not user.is_authenticated():
AttributeError: 'NoneType' object has no attribute 'is_authenticated'

```

**Comment by bendk** [comment]
I haven't seen this one in a while.  Closing, but please reopen if there's still an issue here.
