### ISSUE TITLE
error manually adding a single video to a team

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1438]
testing 82ccc169e3a2 - as a team contributor - attempted to manually add a single video to a team.

Got this error below - but the video was actually added to the team.

I was NOT able to reproduce - after trying to add additional videos to the team as the same contributor, or as an admin.

```
INFO 2014-04-28 00:22:05,272 requests.packages.urllib3.connectionpool Starting new HTTP connection (1): videos-cdn.mozilla.net
INFO 2014-04-28 00:22:05,392 requests.packages.urllib3.connectionpool Starting new HTTP connection (1): videos-cdn.mozilla.net
ERROR 2014-04-28 00:22:06,311 videos-models Data integrity error with video_url_obj 
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/videos/models.py", line 549, in get_or_create_for_url
    assert video_url_obj.video == obj
AssertionError
ERROR 2014-04-28 00:22:06,314 django.request Internal Server Error: /en/teams/add/video/bcove/
Traceback (most recent call last):
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/apps/unisubs/utils/__init__.py", line 55, in wrapper
    output = func(request, *args, **kw)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/apps/unisubs/apps/teams/views.py", line 582, in add_video
    if form.is_valid():
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/forms/forms.py", line 124, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/forms/forms.py", line 115, in _get_errors
    self.full_clean()
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/forms/forms.py", line 270, in full_clean
    self._clean_fields()
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/django/forms/forms.py", line 287, in _clean_fields
    value = field.clean(value)
  File "/opt/apps/unisubs/utils/forms/unisub_video_form.py", line 85, in clean
    self.video, created = Video.get_or_create_for_url(vt=self.vt, user=user)
  File "/opt/apps/unisubs/apps/videos/models.py", line 553, in get_or_create_for_url
    raise e
AssertionError
[28/Apr/2014 00:22:06] "POST /en/teams/add/video/bcove/ HTTP/1.1" 500 237322
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 210, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 268, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 192, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by PCF-Testing** [comment]
Seems to be an isolated case reported very long ago. No other similar issues have been reported. Marking as closed.
