### ISSUE TITLE
errors trying to start unisubs with fix on osx

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1508]
running

macbook-pro:unisubs janet$ fig --verbose up -d db worker cache search queue

I see: 

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 39, in main
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 31, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 50, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 27, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 306, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.project", line 131, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 161, in recreate_containers
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 65, in containers
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.packages.docker.client", line 405, in containers
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.packages.docker.client", line 68, in _get
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/requests.sessions", line 395, in get
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/requests.adapters", line 387, in send
requests.exceptions.Timeout: HTTPConnectionPool(host='localhost', port=4243): Read timed out. (read timeout=60)
macbook-pro:unisubs janet$ 
```

**Comment by bendk** [comment]
Really old bug and not really possible to follow up on now.  Let's close.
