### ISSUE TITLE
figure out video duration for mp4s

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1553]
offshoot of #1480

For team videos, we want to know the video's total duration.

Currently we are able to get this from youtube when the videos are added to the site, but we don't store if for html5 videos or videos from other sources.

Couple options we've considered for this are:

- we could try do a lookup on the video's duration using something like gstreamer (python-gst) that has the Discoverer (gst.pbutils.Discoverer.get_duration())
- check for the duration when the video is opened in the editor and store it at that point.
- can check if we can get the duration from the api of other video hosts like bc, vimeo and kaltura

It would be most ideal to have the ability to look up the videos duration in the case where we'd like to be able to do on-demand orders via a form and want to be able to estimate the cost of subtitles.

If doing the lookup is too slow - potentially we could only do the lookup when there's
1.  an order captions request
2. a team admin (amara-staff) requests a lookup via the ui
3. and otherwise do the lookup via the editor ui as it happens.

**Comment by bendk** [comment]
Dean says that the header data may not be reliable so we would have to download the entire file to get the duration.

**Comment by syl22-00** [comment]
This is done in gh-1553:
* For youtube, it uses non-API calls to youtube
* For public Vimeo videos, it uses non-API calls to vimeo
* For direct files (mp4, mp3, flv), it uses the header

**Comment by PCF-Testing** [comment]
Breaks for me on longer YouTube videos - no duration gets stored. Example: https://www.youtube.com/watch?v=xY4aOHTjGTM

**Comment by PCF-Testing** [comment]
Also, do I get it right that for password-protected Vimeo videos the duration will be unavailable?

**Comment by syl22-00** [comment]
* For longer youtube videos, I'll check if that can be fixed, but it should not really matter for now as it is only for dev environement. In production, it uses the API.
* You are correct for non-public vimeo videos, although there might be cases where we'll be able to get it using the API. Will be investigated in another ticket

**Comment by syl22-00** [comment]
@PCF-Testing For longer youtube duration, it is actually an issue in our code when getting duration via API. You probably have youtube's API key set up so you are hitting it in your dev environment.

I pushed a fix in the branch. Duration without API calls are fine for longer videos

**Comment by syl22-00** [comment]
The fix includes a new Python library to be installed, so the image must be rebuilt

**Comment by PCF-Testing** [comment]
Breaks on some MP4 videos from S3 - gave examples in a slack convo.

**Comment by syl22-00** [comment]
@PCF-Testing for these 3 erroneous values:
* 2 of them were because of unsupported codecs by the installed version of lib-avconv, which actually does not matter to check video duration. So I fixed this by just keeping the standard error, it can now be parsed successfully.
* The remaining one (incorrect length) was because of inconsistencies between lengths of streams. I believe I fixed that too.

**Comment by PCF-Testing** [comment]
Fixed for the 3 videos I have referred to earlier.

Got it wrong for https://s3.amazonaws.com/amara-video/upload/v2b/1_week/1283_Windows+8+%26+Windows+8.1+f%C3%BCr+Anwender/1283_10_09.mp4 - 0:01 instead of the expected 4:31

**Comment by syl22-00** [comment]
Got this one correct too now.

**Comment by PCF-Testing** [comment]
Looks good to me now related to video duration.

Last thing: the changes have broken a few tests that need fixing, too:

======================================================================
ERROR: test_invalid (externalsites.tests.test_youtube_api.TestTimeParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/externalsites/tests/test_youtube_api.py", line 238, in test_invalid
    self.assertEqual(google._parse_8601_duration('foo'), None)
AttributeError: 'module' object has no attribute '_parse_8601_duration'

======================================================================
ERROR: test_with_minutes (externalsites.tests.test_youtube_api.TestTimeParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/externalsites/tests/test_youtube_api.py", line 232, in test_with_minutes
    self.assertEqual(google._parse_8601_duration('PT10M10S'), 610)
AttributeError: 'module' object has no attribute '_parse_8601_duration'

======================================================================
ERROR: test_without_minutes (externalsites.tests.test_youtube_api.TestTimeParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/externalsites/tests/test_youtube_api.py", line 235, in test_without_minutes
    self.assertEqual(google._parse_8601_duration('PT10S'), 10)
AttributeError: 'module' object has no attribute '_parse_8601_duration'

======================================================================
ERROR: test_get_video_info_no_items (externalsites.tests.test_youtube_api.YouTubeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/externalsites/tests/test_youtube_api.py", line 177, in test_get_video_info_no_items
    google.get_video_info('test-video-id')
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/opt/apps/unisubs/apps/externalsites/google.py", line 406, in get_video_info
    p = pafy.new(video_id)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 144, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 533, in __init__
    self.videoid = extract_video_id(video_url)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 182, in extract_video_id
    raise ValueError(err % url)
ValueError: Need 11 character video id or the URL of the video. Got //test-video-id

======================================================================
ERROR: test_get_video_invalid_body (externalsites.tests.test_youtube_api.YouTubeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/externalsites/tests/test_youtube_api.py", line 160, in test_get_video_invalid_body
    google.get_video_info('test-video-id')
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/opt/apps/unisubs/apps/externalsites/google.py", line 406, in get_video_info
    p = pafy.new(video_id)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 144, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 533, in __init__
    self.videoid = extract_video_id(video_url)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 182, in extract_video_id
    raise ValueError(err % url)
ValueError: Need 11 character video id or the URL of the video. Got //test-video-id

======================================================================
ERROR: test_get_video_info_exception (videos.tests.test_video_types.YoutubeVideoTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/utils/test_utils/monkeypatch.py", line 182, in wrapper
    return func(self, mock_obj, *args, **kwargs)
  File "/opt/apps/unisubs/apps/videos/tests/test_video_types.py", line 87, in test_get_video_info_exception
    'http://www.youtube.com/watch?v=_ShmidkrcY0')
  File "/opt/apps/unisubs/apps/videos/models.py", line 567, in get_or_create_for_url
    vt.set_values(obj, **kwargs)
  File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 79, in set_values
    video_info = self.get_video_info()
  File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 75, in get_video_info
    self._video_info = google.get_video_info(self.video_id)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1010, in _mock_call
    raise effect
APIError

**Comment by syl22-00** [comment]
I fixed the test, making a PR now

**Comment by PCF-Testing** [comment]
PR merged, changing status to Waiting for deploy.

**Comment by PCF-Testing** [comment]
Deployed.
