### ISSUE TITLE
token error trying to add credit to team video

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1557]
Testing on branch gh-1488: e4b2900

```
ERROR 2014-06-23 10:07:30,809 sentry.errors No servers configured, and sentry not installed. Cannot send message
[2014-06-23 10:07:30,811: ERROR/MainProcess] Task externalsites.tasks.add_amara_credit[75bf2755-f42c-43c1-9b27-b114d66a9a5b] raised exception: KeyError('access_token',)
Traceback (most recent call last):
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ve/unisubs/local/lib/python2.7/site-packages/celery/task/trace.py", line 403, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/apps/unisubs/apps/externalsites/tasks.py", line 130, in add_amara_credit
    youtubecredit.add_credit_to_video_url(video_url, account)
  File "/opt/apps/unisubs/apps/externalsites/youtubecredit.py", line 49, in add_credit_to_video_url
    access_token = youtube.get_new_access_token(account.oauth_refresh_token)
  File "/opt/apps/unisubs/utils/youtube.py", line 149, in get_new_access_token
    return response.json['access_token']
KeyError: 'access_token'
[2014-06-23 10:07:31,029: INFO/MainProcess] Finished 'http://172.17.42.1:51001/solr/update/?commit=true' (POST) with body '<add><doc>' in 0.376 seconds.

```

I have my personal account where I added some yt videos.
Then I added those videos to a team and synced up 2 different yt accounts, 1 of which  is the actual video owner.

When I added subtitles to the video, I got the sync error above in  in add_credit_to_video_url

![image](https://cloud.githubusercontent.com/assets/299270/3359500/da62262e-fae8-11e3-92f6-a0da91db8dc4.png)

![image](https://cloud.githubusercontent.com/assets/299270/3359529/2c63272a-fae9-11e3-81ed-2ebe74193cd5.png)

![image](https://cloud.githubusercontent.com/assets/299270/3359556/75570154-fae9-11e3-8c84-d406a3b974ed.png)

I think we actually shouldn't be trying to add the credit because it's a team video, but if we do add that as an option for teams, we want to be sure we are using the correct account.

**Comment by bendk** [comment]
No updates in a while, closing this one.
