### ISSUE TITLE
api-refactory branch: fails with language codes that include region

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2009]
Attempting to retrieve languages or save subtitles where the language code is not the simple 2-letter iso code fails.

- [ ] 1. Added a new language, added subtitles in editor, clicked save:

Result:  Error for pt-br, or es-mx, successful for nl or other simple lang.

```
app_1 | [05/Feb/2015 03:04:37] "GET /api2/partners/videos/6YJ6Y8SlOdRV/languages/bg/subtitles/?format=json&sub_format=dfxp&version=1 HTTP/1.1" 200 1493
app_1 | WARNING 2015-02-05 03:04:41,090 base 71 139754542462720 Not Found: /api/videos/6YJ6Y8SlOdRV/languages/es-ar/subtitles/actions/
app_1 | [05/Feb/2015 03:04:41] "POST /api/videos/6YJ6Y8SlOdRV/languages/es-ar/subtitles/actions/ HTTP/1.1" 404 13261
```

- [ ] 2. Used languages lookup, */api/videos/6YJ6Y8SlOdRV/languages/* 

Worked fine if there were no langs with locale, failed once I created pt-br.

```
app_1 | ERROR 2015-02-05 03:07:37,833 base 71 139754899777280 Internal Server Error: /api/videos/6YJ6Y8SlOdRV/languages/
app_1 | Traceback (most recent call last):
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1 |     response = callback(request, *callback_args, **callback_kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
app_1 |     return view_func(*args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 85, in view
app_1 |     return self.dispatch(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
app_1 |     response = self.handle_exception(exc)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
app_1 |     response = handler(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 46, in list
app_1 |     return Response(serializer.data)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 463, in data
app_1 |     ret = super(Serializer, self).data
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 212, in data
app_1 |     self._data = self.to_representation(self.instance)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 432, in to_representation
app_1 |     ret[field.field_name] = field.to_representation(attribute)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 565, in to_representation
app_1 |     self.child.to_representation(item) for item in iterable
app_1 |   File "/opt/apps/unisubs/apps/api/views/subtitles.py", line 226, in to_representation
app_1 |     language)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 432, in to_representation
app_1 |     ret[field.field_name] = field.to_representation(attribute)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 1241, in to_representation
app_1 |     return method(value)
app_1 |   File "/opt/apps/unisubs/apps/api/views/subtitles.py", line 221, in get_resource_uri
app_1 |     'language_code': language.language_code,
app_1 |   File "/opt/apps/unisubs/apps/localeurl/__init__.py", line 18, in reverse
app_1 |     path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 500, in reverse
app_1 |     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 420, in _reverse_with_prefix
app_1 |     "arguments '%s' not found." % (lookup_view_s, args, kwargs))
app_1 | NoReverseMatch: Reverse for 'video-language-detail' with arguments '()' and keyword arguments '{'video_id': u'6YJ6Y8SlOdRV', 'language_code': u'es-ar'}' not found.
app_1 | [05/Feb/2015 03:07:38] "GET /api/videos/6YJ6Y8SlOdRV/languages/ HTTP/1.1" 500 223406
```

**Comment by jdragojevic** [comment]
checked this and created a webdriver test.
