### ISSUE TITLE
Implement collab dashboard for non-members

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2083]
We should be able to create collab teams and configure if the team is visible to non-members.  Currently all collab teams are private.

This would require having some sort of a welcome page for non-members with the join-team button like we have for old style team, vs showing the available collabs with join collab buttons to non-members.

**Comment by bendk** [comment]
We currently list the team in the directory, but if you click on it you get a 403 error.  We should show a welcome page.

**Comment by bendk** [comment]
Talked with janet a bit about this one.  Here's what I'm thinking:

* The page inherits from the regular base.html template, not the team one.  So it doesn't look like it's in the team area and doesn't show the tabs, team info, etc.
* Page shows a welcome message, which is configurable from the messages tab in the team settings
* Page shows a link to join the team
* Show the videos if is_visible=True
* Add a setting for collab-teams to allow admins to change is_visible from the team setting

**Comment by bendk** [comment]
Initial implementation is done in the gh-2083 branch on unisubs/amara enterprise.  As always, I would love to rework our base CSS, but it looks okay to me.

**Comment by jdragojevic** [comment]
- [ ] 1. For an application team, clicking the Submit application button on the form gives an error in the console: unisubs.example.com/:1885 Uncaught ReferenceError: TeamsApi is not defined

**Comment by jdragojevic** [comment]
- [ ] 2. Get an error opening the dash for an application-only team:
```
 ERROR 2015-03-23 06:45:00,346 base 180 140533056661248 Internal Server Error: /en/teams/collllab/
app_1 | Traceback (most recent call last):
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1 |     response = callback(request, *callback_args, **callback_kwargs)
app_1 |   File "/opt/apps/unisubs/apps/teams/views.py", line 1559, in dashboard
app_1 |     return team.new_workflow.dashboard_view(request, team)
app_1 |   File "/opt/apps/unisubs/amara-enterprise/collab/views.py", line 81, in team_dashboard
app_1 |     return team_welcome(request, team)
app_1 |   File "/opt/apps/unisubs/amara-enterprise/collab/views.py", line 93, in team_welcome
app_1 |     'welcome_message': team.settings.get_message('pagetext_welcome'),
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 44, in render
app_1 |     return HttpResponse(loader.render_to_string(*args, **kwargs),
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 176, in render_to_string
app_1 |     return t.render(context_instance)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
app_1 |     return self._render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 63, in instrumented_test_render
app_1 |     return self.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
app_1 |     return compiled_parent._render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 63, in instrumented_test_render
app_1 |     return self.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
app_1 |     result = block.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 282, in render
app_1 |     return nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 426, in render
app_1 |     raise e
app_1 | NoReverseMatch: u'"teams' is not a registered namespace
app_1 | [23/Mar/2015 06:45:00] "GET /en/teams/collllab/ HTTP/1.1" 500 511635
```

**Comment by bendk** [comment]
Both of those should be fixed with 04aac09

**Comment by jdragojevic** [comment]
- [ ] clicking the join our team link as a logged in user - results in no action.

<a href="#" data-modal="language_modal" id="lang_select_btn">Join our team now!</a>

Expected: the language selection dialog should be displayed.

**Comment by bendk** [comment]
This is implemented in the new-teams-styles branch.

I fixed the join button link, but didn't implement the dialog.  I made #2192 for that.

**Comment by jdragojevic** [comment]
this was deployed.
