### ISSUE TITLE
local instance feed import: Settings' object has no attribute 'STANFORD_FEED_LIST_URL'

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2094]
Seeing this locally - not sure what caused it but it seems to prevent my feeds from pulling in videos.

```
worker_1 | [2015-03-06 10:28:38,790: ERROR/MainProcess] Task stanford.tasks.import_all_feeds[5ba8c77d-d610-424e-b989-90a9a9ebd2e2] raised exception: AttributeError("'Settings' object has no attribute 'STANFORD_FEED_LIST_URL'",)
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/stanford/tasks.py", line 36, in import_all_feeds
worker_1 |     _import_all_feeds(force=force)
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/stanford/multivideopuller.py", line 256, in import_all_feeds
worker_1 |     feeds = get_feeds()
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/stanford/multivideopuller.py", line 243, in get_feeds
worker_1 |     STANFORD_FEED_LIST_URL = getattr(settings, "STANFORD_FEED_LIST_URL")
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 185, in inner
worker_1 |     return func(self._wrapped, *args)
worker_1 | AttributeError: 'Settings' object has no attribute 'STANFORD_FEED_LIST_URL'

```

**Comment by bendk** [comment]
I snuck in a change to amara-enterprise that should fix the exception.

**Comment by bendk** [comment]
I don't think this was a real issue.  The setting would be set on production, and even when the exception did occur I don't think it messed up other code.
