### ISSUE TITLE
gh-2044 branch: global name 'language_code' is not defined

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2118]
few unittest failures:

https://builder.amara.org/job/amara/526/testReport/

Stacktrace

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 340, in run
    testMethod()
  File "/opt/apps/unisubs/apps/teams/tests/test_notes.py", line 40, in test_workflow_returns_team_editor_notes
    editor_notes = workflow.get_editor_notes('en')
  File "/opt/apps/unisubs/apps/teams/workflows/old/subtitleworkflows.py", line 172, in get_editor_notes
    language_code)
  File "/opt/apps/unisubs/apps/teams/workflows/notes.py", line 34, in __init__
    self.notes = self.fetch_notes()
  File "/opt/apps/unisubs/apps/teams/workflows/notes.py", line 39, in fetch_notes
    language_code=language_code)
NameError: global name 'language_code' is not defined

**Comment by jdragojevic** [comment]
fixed in the branch.
