### ISSUE TITLE
Allow method to create a new user with a unique username

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2126]
We should add an field to the users API to allow the client to create a new user, even if the username is taken.  This avoids forcing API clients to have logic on their part which checks if usernames exist and re-creates them.  I think this would be enabled by having a POST field called find_uinque_username or something like that.  If it was specified in the request, the the following logic would kick in:

* Try the username specified in the request
* If that username is taken then we try new usernames by appending 01, 02, 03... etc to the end of the useranme.
* If the username contains the "@" char, we insert the number before the "@"
* If we find a unique username, then we return an HTTP 200 response.  Clients will need to make sure they check the username returned since it could be different than the one they passed us.
* If we reach 30 tries and there are still no unique usernames, then we return a HTTP 400 response.

**Comment by bendk** [comment]
Implemented in the gh-2126 branch.  I changed the algorithm a bit so that the API will always find a unique username.  The new algorithm tries usernames like this:

* Try the initial username
* Try the initial username with 01, 02, 03, ..., 99 appended
* Try the initial username with a random 6-character strings appended.

Step 3 should find a unique name fairly quickly.

**Comment by jdragojevic** [comment]
testing on this branch for the 30 char username: 
if I try to create a long username I get an error via the ui.   When I create a long username via the test client it's actually creating the user with the long username.

```
 ERROR 2015-03-31 11:27:30,050 base 68 140464470562560 Internal Server Error: /api/users/
app_1 | Traceback (most recent call last):
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1 |     response = callback(request, *callback_args, **callback_kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
app_1 |     return view_func(*args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 85, in view
app_1 |     return self.dispatch(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
app_1 |     response = self.handle_exception(exc)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
app_1 |     response = handler(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
app_1 |     self.perform_create(serializer)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 26, in perform_create
app_1 |     serializer.save()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 164, in save
app_1 |     self.instance = self.create(validated_data)
app_1 |   File "/opt/apps/unisubs/apps/api/views/users.py", line 177, in create
app_1 |     created_by=self.context['request'].user, **validated_data)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 137, in create
app_1 |     return self.get_query_set().create(**kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 377, in create
app_1 |     obj.save(force_insert=True, using=self.db)
app_1 |   File "/opt/apps/unisubs/apps/auth/models.py", line 171, in save
app_1 |     super(CustomUser, self).save(*args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 463, in save
app_1 |     self.save_base(using=using, force_insert=force_insert, force_update=force_update)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 506, in save_base
app_1 |     self.save_base(cls=parent, origin=org, using=using)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 551, in save_base
app_1 |     result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 203, in _insert
app_1 |     return insert_query(self.model, objs, fields, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1593, in insert_query
app_1 |     return query.get_compiler(using=using).execute_sql(return_id)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
app_1 |     cursor.execute(sql, params)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 40, in execute
app_1 |     return self.cursor.execute(sql, params)
app_1 |   File "/opt/apps/unisubs/middleware.py", line 97, in execute
app_1 |     return super(MetricsCursorWrapper, self).execute(query, params)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 114, in execute
app_1 |     return self.cursor.execute(query, args)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 207, in execute
app_1 |     if not self._defer_warnings: self._warning_check()
app_1 |   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 117, in _warning_check
app_1 |     warn(w[-1], self.Warning, 3)
app_1 | Warning: Data truncated for column 'username' at row 1
app_1 | [31/Mar/2015 11:27:30] "POST /api/users/ HTTP/1.1" 500 231414
```

**Comment by bendk** [comment]
Just added a check for the username length.  It should be <= 30 chars normally and <= 24 chars when find_unique_username is passed in.
