### ISSUE TITLE
Project initialization from docker-compose

### ISSUE THREAD

**Issue by shell** [pculture/unisubs#2183]
Hello,

I was trying to bootstrap your project with docker container on Mac.
I was following instructions and then on the step 7 I couldn't access site at  http://unisubs.example.com:8000.

With some investigation I pulled out this from logs:

```bash
worker_1 | [2015-04-22 15:38:58,450: INFO/MainProcess] consumer: Connected to amqplib://guest@172.17.0.51:5672//.
worker_1 | [2015-04-22 15:38:58,451: DEBUG/MainProcess] using channel_id: 1
worker_1 | [2015-04-22 15:38:58,456: DEBUG/MainProcess] Channel open
worker_1 | [2015-04-22 15:38:58,630: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
worker_1 | [2015-04-22 15:38:58,632: DEBUG/MainProcess] using channel_id: 2
worker_1 | [2015-04-22 15:38:58,635: DEBUG/MainProcess] Channel open
worker_1 | [2015-04-22 15:38:58,681: DEBUG/MainProcess] consumer: Ready to accept tasks!
worker_1 | [2015-04-22 15:38:59,013: DEBUG/Beat] Celerybeat: Ticking with max interval->5.00 seconds
worker_1 | [2015-04-22 15:38:59,029: DEBUG/MainProcess] Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
worker_1 | [2015-04-22 15:38:59,035: DEBUG/MainProcess] Open OK! known_hosts []
worker_1 | [2015-04-22 15:38:59,046: DEBUG/Beat] Celerybeat: Waking up in 5.00 seconds.
worker_1 | [2015-04-22 15:39:04,055: DEBUG/Beat] Celerybeat: Waking up in 5.00 seconds.
worker_1 | [2015-04-22 15:39:09,065: DEBUG/Beat] Celerybeat: Waking up in 5.00 seconds.
worker_1 | [2015-04-22 15:39:14,076: WARNING/Beat] /usr/local/lib/python2.7/dist-packages/djcelery/schedulers.py:164: RuntimeWarning: Database gave error: OperationalError(2003, "Can't connect to MySQL server on '172.17.0.49' (111)")
worker_1 |   warn(RuntimeWarning("Database gave error: %r" % (exc, )))
worker_1 | [2015-04-22 15:39:14,082: DEBUG/Beat] Celerybeat: Waking up in 5.00 seconds.
worker_1 | [2015-04-22 15:39:27,762: ERROR/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 390, in start
worker_1 |     self.consume_messages()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 474, in consume_messages
worker_1 |     readers[fileno](fileno, event)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 292, in drain_nowait
worker_1 |     self.drain_events(timeout=0)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 281, in drain_events
worker_1 |     return self.transport.drain_events(self.connection, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 761, in connection
worker_1 |     self._connection = self._establish_connection()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 720, in _establish_connection
worker_1 |     conn = self.transport.establish_connection()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py", line 345, in establish_connection
worker_1 |     connect_timeout=conninfo.connect_timeout)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py", line 151, in __init__
worker_1 |     super(Connection, self).__init__(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/amqplib/client_0_8/connection.py", line 129, in __init__
worker_1 |     self.transport = create_transport(host, connect_timeout, ssl)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/amqplib/client_0_8/transport.py", line 281, in create_transport
worker_1 |     return TCPTransport(host, connect_timeout)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/amqplib/client_0_8/transport.py", line 85, in __init__
worker_1 |     raise socket.error, msg
worker_1 | error: [Errno 111] Connection refused
worker_1 | [2015-04-22 15:39:27,774: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
worker_1 | [2015-04-22 15:39:27,775: DEBUG/MainProcess] consumer: Heart: Going into cardiac arrest...
worker_1 | [2015-04-22 15:39:27,776: DEBUG/MainProcess] consumer: Cancelling task consumer...
worker_1 | [2015-04-22 15:39:27,777: DEBUG/MainProcess] consumer: Shutting down event dispatcher...
worker_1 | [2015-04-22 15:39:27,777: DEBUG/MainProcess] consumer: Cancelling broadcast consumer...
worker_1 | [2015-04-22 15:39:27,777: DEBUG/MainProcess] consumer: Closing consumer channel...
worker_1 | [2015-04-22 15:39:27,778: DEBUG/MainProcess] consumer: Closing broadcast channel...
worker_1 | [2015-04-22 15:39:27,779: DEBUG/MainProcess] consumer: Closing broker connection...
worker_1 | [2015-04-22 15:39:27,781: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: [Errno 111] Connection refused.
worker_1 | Trying again in 2.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:39:33,784: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: timed out.
worker_1 | Trying again in 4.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:39:41,793: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: timed out.
worker_1 | Trying again in 6.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:39:51,807: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: timed out.
worker_1 | Trying again in 8.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:40:03,823: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: timed out.
worker_1 | Trying again in 10.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:40:17,842: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: timed out.
worker_1 | Trying again in 12.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:40:25,188: WARNING/Beat] /usr/local/lib/python2.7/dist-packages/djcelery/schedulers.py:164: RuntimeWarning: Database gave error: OperationalError(2003, "Can't connect to MySQL server on '172.17.0.49' (113)")
worker_1 |   warn(RuntimeWarning("Database gave error: %r" % (exc, )))
worker_1 | [2015-04-22 15:40:25,189: INFO/Beat] Scheduler: Sending due task gauge_billing_records (videos.tasks.gauge_billing_records)
worker_1 | [2015-04-22 15:40:31,188: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: [Errno 113] No route to host.
worker_1 | Trying again in 14.00 seconds...
worker_1 |
worker_1 | [2015-04-22 15:40:46,189: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.51:5672//: [Errno 113] No route to host.
worker_1 | Trying again in 16.00 seconds...
```

More info on that:
```bash
➜  unisubs2 [staging*] docker-compose ps
      Name                     Command               State                         Ports
--------------------------------------------------------------------------------------------------------------
unisubs2_app_1      /usr/bin/env /usr/bin/pyth ...   Up      0.0.0.0:8000->8000/tcp
unisubs2_cache_1    /usr/local/bin/memcached - ...   Up      0.0.0.0:32809->11211/tcp
unisubs2_db_1       /usr/local/bin/run               Up      0.0.0.0:32810->3306/tcp
unisubs2_queue_1    /usr/sbin/rabbitmq-server        Up      0.0.0.0:32811->15672/tcp, 0.0.0.0:32812->5672/tcp
unisubs2_search_1   java -jar start.jar              Up      0.0.0.0:32808->8983/tcp
unisubs2_worker_1   /usr/bin/env /usr/bin/pyth ...   Up      8000/tcp
```

and this:

```bash
➜  unisubs2 [staging*] boot2docker ssh
Boot2Docker version 1.6.0, build master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
Docker version 1.6.0, build 4749651
docker@boot2docker:~$ sudo netstat -ntpl | grep docker
tcp        0      0 :::8000                 :::*                    LISTEN      1790/docker-proxy
tcp        0      0 :::32808                :::*                    LISTEN      1445/docker-proxy
tcp        0      0 :::2376                 :::*                    LISTEN      1273/docker
tcp        0      0 :::32809                :::*                    LISTEN      1502/docker-proxy
tcp        0      0 :::32810                :::*                    LISTEN      1546/docker-proxy
tcp        0      0 :::32811                :::*                    LISTEN      1653/docker-proxy
tcp        0      0 :::32812                :::*                    LISTEN      1661/docker-proxy
docker@boot2docker:~$
```

Did I miss something in tutorial or it's configuration issue?

Also it seems that you can omit this step from tutorial `docker-compose up -d db worker cache search queue` because docker-compose (re)running linked services anyways.

**Comment by shell** [comment]
solved by adding "- worker" to app:links in docker-compose.yml and starting it all by one command

**Comment by shell** [comment]
also on mac, instead of going http://unisubs.example.com:8000, you need to go to boot2docker ip and port 8000

**Comment by bendk** [comment]
I'm not sure why adding worker to app:links solved this one.  The reason it's not listed there is that you shouldn't need one for the other.  The webapp and the worker never directly communicate, the app  pushes messages to the queue then the worker works on them.  You should be able to run the app without the worker and none of the core functionality will break the worst that will happen are things like search index updates not happening.

I haven't used boot2docker, but you should make sure unisubs.example.com points to the IP address that the server is running on.  Sometimes we need to link to the webserver host and for development that should be unisubs.example.com.

**Comment by bendk** [comment]
After checking this out some more, I realize there was an issue with this.  I'm not sure what happened but somewhere along the lines when we switched to docker-compose and started using newer docker versions it crept in there.

The simplest way to do things is your suggested way where you start all containers together.  I just pushed some changes that do that.  Now you can use "dev up" to start them all.  Also "dev up --ssl" starts them all with the app running in ssl mode.
