### ISSUE TITLE
new-api-switchover branch: handle lang codes with upper case

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2213]
There was some handling for languague code casing in api2/partners - so that if for example a subtitle upload request was made for de-CH (a plausible vimeo use case) we would upload the subs.

In the switchover branch - using de-CH results in an error: 

`ValidationError: [u'Subtitle Language de-CH should be a valid code.']`, while de-ch works fine.

Both should be acceptable.

**Comment by bendk** [comment]
I changed this for language_code on the subtitle language resource and primary_audio_language_code for the video resource.

I checked and you can use any case when constructing the URL (/api/videos/abcdef/languages/pt-BR works).

Are there any other cases we need to cover?

**Comment by jdragojevic** [comment]
still seeing this: 
```
INFO 2015-05-07 13:32:26,156 data_helpers 1 140486436435776 /api2/partners/videos/aoCzbm3YPTqi/languages/
INFO 2015-05-07 13:32:26,157 data_helpers 1 140486436435776 {'X-apikey': 'f2b8291eeab8715ca9bf001f72549a7e3e24fc15', 'Content-Type': 'application/json', 'X-api-username': 'vimeo', 'Accept': 'application/json'}
INFO 2015-05-07 13:32:26,187 data_helpers 1 140486436435776 http://localhost:8090/
INFO 2015-05-07 13:32:26,187 data_helpers 1 140486436435776 /api2/partners/videos/aoCzbm3YPTqi/languages/de-CH/subtitles/
INFO 2015-05-07 13:32:26,189 data_helpers 1 140486436435776 {'X-apikey': u'f2b8291eeab8715ca9bf001f72549a7e3e24fc15', 'Content-Type': 'application/json', 'X-api-username': 'vimeo', 'Accept': 'application/json'}
ERROR 2015-05-07 13:32:26,214 base 1 140486262011648 Internal Server Error: /api2/partners/videos/aoCzbm3YPTqi/languages/de-CH/subtitles/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/generics.py", line 260, in post
    return self.create(request, *args, **kwargs)
  File "/opt/apps/unisubs/apps/api/views/subtitles.py", line 680, in create
    return super(SubtitlesView, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 164, in save
    self.instance = self.create(validated_data)
  File "/opt/apps/unisubs/apps/api/views/subtitles.py", line 611, in create
    origin=origin)
  File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 546, in add_subtitles
    created, note, origin, metadata, action)
  File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 398, in _add_subtitles
    sl.save()
  File "/opt/apps/unisubs/apps/subtitles/models.py", line 482, in save
    self.language_code)
ValidationError: [u'Subtitle Language de-CH should be a valid code.']
INFO 2015-05-07 13:32:26,246 test_open_editor 1 140486436435776 
```

**Comment by bendk** [comment]
I couuldn't easily reproduce this one.  I think it only happens when we are trying to create a version when the language hasn't been created.  I believe the change above should fix it though.
