### ISSUE TITLE
Video API Exception

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2228]
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 711, in __iter__
File "/usr/local/lib/python2.7/dist-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 1087, in __call__
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 241, in __call__
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
File "/usr/local/lib/python2.7/dist-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 85, in view
File "/usr/local/lib/python2.7/dist-packages/newrelic-2.50.0.39/newrelic/hooks/component_djangorestframework.py", line 27, in _nr_wrapper_APIView_dispatch_
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 40, in list
File "/opt/apps/unisubs/apps/api/views/videos.py", line 489, in get_queryset
File "/opt/apps/unisubs/apps/videos/types/base.py", line 97, in video_type_for_url
File "/opt/apps/unisubs/apps/videos/types/dailymotion.py", line 54, in matches_video_url
File "/opt/apps/unisubs/apps/videos/types/dailymotion.py", line 82, in get_metadata
```

Looks like it's an issue with the dailymotion video URL code

**Comment by bendk** [comment]
https://rpm.newrelic.com/accounts/207361/applications/3323332/traced_errors/2835685635

**Comment by bendk** [comment]
The gh-2228 branch should fix this one.

**Comment by jdragojevic** [comment]
this merged/deployed on friday 22/5
