### ISSUE TITLE
error opening project for edit

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2230]
```
5-20 06:15:26,706 base 1666 140657289590528 Internal Server Error: /en/teams/old-style-open/settings/projects/georgia/edit/
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1    |     response = callback(request, *callback_args, **callback_kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
app_1    |     return view_func(request, *args, **kwargs)
app_1    |   File "/opt/apps/unisubs/apps/teams/new_views.py", line 62, in wrapper
app_1    |     return view_func(request, team, *args, **kwargs)
app_1    |   File "/opt/apps/unisubs/apps/teams/new_views.py", line 180, in edit_project
app_1    |     return old_views.edit_project(request, team, project_slug)
app_1    |   File "/opt/apps/unisubs/utils/__init__.py", line 56, in wrapper
app_1    |     output = func(request, *args, **kw)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
app_1    |     return view_func(request, *args, **kwargs)
app_1    |   File "/opt/apps/unisubs/apps/teams/views.py", line 2073, in edit_project
app_1    |     project_list_url = reverse('teams:settings_projects', args=[], kwargs={'slug': slug})
app_1    |   File "/opt/apps/unisubs/apps/localeurl/__init__.py", line 18, in reverse
app_1    |     path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 500, in reverse
app_1    |     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 420, in _reverse_with_prefix
app_1    |     "arguments '%s' not found." % (lookup_view_s, args, kwargs))
app_1    | NoReverseMatch: Reverse for 'settings_projects' with arguments '()' and keyword arguments '{'slug': <Team: old style open>}' not found.
app_1    | [20/May/2015 06:15:27] "GET /en/teams/old-style-open/settings/projects/georgia/edit/ HTTP/1.1" 500 230490
```

**Comment by bendk** [comment]
This one was pretty trivial, I just pushed it directly to staging.
