### ISSUE TITLE
Remove blip video type

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2327]
The service closed, so we should make sure nobody can submit those videos anymore.

**Comment by syl22-00** [comment]
Should be done in branch gh-2327

**Comment by PCF-Testing** [comment]
DailyMotion tests break on the branch:

======================================================================
ERROR: test_dailymotion_urls (videos.tests.test_forms.TestVideoForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/videos/tests/test_forms.py", line 70, in test_dailymotion_urls
    self._test_urls(self.daily_motion_urls)
  File "/opt/apps/unisubs/apps/videos/tests/test_forms.py", line 47, in _test_urls
    video = form.save()
  File "/opt/apps/unisubs/apps/videos/forms.py", line 171, in save
    obj, created = Video.get_or_create_for_url(video_url, self._video_type, self.user)
  File "/opt/apps/unisubs/apps/videos/models.py", line 552, in get_or_create_for_url
    vt.set_values(obj, **kwargs)
  File "/opt/apps/unisubs/apps/videos/types/dailymotion.py", line 55, in set_values
    metadata = self.get_metadata(self.video_id)
  File "/opt/apps/unisubs/apps/videos/types/dailymotion.py", line 76, in get_metadata
    raise VideoTypeError(_(u'Video is unavailable'))
VideoTypeError: <django.utils.functional.__proxy__ object at 0x7f497edf1d50>

======================================================================
ERROR: test_type (videos.tests.test_video_types.DailymotionVideoTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/videos/tests/test_video_types.py", line 157, in test_type
    video, created = Video.get_or_create_for_url(url)
  File "/opt/apps/unisubs/apps/videos/models.py", line 552, in get_or_create_for_url
    vt.set_values(obj, **kwargs)
  File "/opt/apps/unisubs/apps/videos/types/dailymotion.py", line 55, in set_values
    metadata = self.get_metadata(self.video_id)
  File "/opt/apps/unisubs/apps/videos/types/dailymotion.py", line 76, in get_metadata
    raise VideoTypeError(_(u'Video is unavailable'))
VideoTypeError: <django.utils.functional.__proxy__ object at 0x7f497e778190>

**Comment by PCF-Testing** [comment]
On submitting DM video:

VideoTypeError at /videos/create/
Video is unavailable
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/videos/create/
Django Version:	1.4.21
Exception Type:	VideoTypeError
Exception Value:	
Video is unavailable
Exception Location:	/opt/apps/unisubs/apps/videos/types/dailymotion.py in get_metadata, line 76

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/unisubs/apps/videos/views.py" in create
  214.             video = video_form.save()
File "/opt/apps/unisubs/apps/videos/forms.py" in save
  171.         obj, created = Video.get_or_create_for_url(video_url, self._video_type, self.user)
File "/opt/apps/unisubs/apps/videos/models.py" in get_or_create_for_url
  552.             vt.set_values(obj, **kwargs)
File "/opt/apps/unisubs/apps/videos/types/dailymotion.py" in set_values
  55.         metadata = self.get_metadata(self.video_id)
File "/opt/apps/unisubs/apps/videos/types/dailymotion.py" in get_metadata
  76.                 raise VideoTypeError(_(u'Video is unavailable'))

Exception Type: VideoTypeError at /videos/create/
Exception Value: Video is unavailable

**Comment by PCF-Testing** [comment]
UPD: DailyMotion issue also happens on staging and production. Will be tracked in https://github.com/pculture/unisubs/issues/2353.

Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Deployed.
