### ISSUE TITLE
Automatic import of videos from individual YouTube channels stops after a few videos

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2456]
Reported in https://support.amara.org/helpdesk/tickets/83001, confirmed on production, staging, and a local instance.

If a YouTube channel with lots of videos is connected to an Amara account, the expected behaviour is to automatically import to Amara all the public and unlisted videos from the channel (excluding private ones) and to add "Help us caption & translate this video!" link to the videos' descriptions.

However, the import process halts after a few videos and never resumes. There is no good way to complete the automatic import.

Example:
https://www.youtube.com/channel/UC2A6Mw5JqajnERZWahYovpg/videos?shelf_id=0&view=0&sort=dd (55 videos)
Imported to production - 5 videos: https://www.amara.org/en/profiles/videos/amara.test.1@gmail.com/
Imported to staging - 5 videos:
https://staging.amara.org/en/profiles/videos/amara.test.1@gmail.com/

**Comment by bendk** [comment]
This should be fixed in the branch.  I think we should still have some limit on the number of videos.  I set it to 1000 in the branch, but any number is fine with me.

**Comment by PCF-Testing** [comment]
Verified locally with 55 videos imported from a linked channel.

One test is broken:

FAIL: test_get_uploaded_video_ids (externalsites.tests.test_youtube_api.YouTubeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_youtube_api.py", line 111, in test_get_uploaded_video_ids
    video_ids = google.get_uploaded_video_ids('test-channel-id')
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/opt/apps/amara/apps/externalsites/google.py", line 276, in get_uploaded_video_ids
    None)
  File "/opt/apps/amara/apps/externalsites/google.py", line 293, in _get_uploaded_video_ids
    params=params)
  File "/opt/apps/amara/apps/externalsites/google.py", line 245, in _make_youtube_api_request
    return _make_api_request(method, access_token, url, **kwargs)
  File "/opt/apps/amara/apps/externalsites/google.py", line 227, in _make_api_request
    response = requests.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/opt/apps/amara/utils/test_utils/requests.py", line 119, in mock_request
    return self.check_request(method.lower(), url, params, data, headers)
  File "/opt/apps/amara/utils/test_utils/requests.py", line 131, in check_request
    assert_equal(params, expected.params)
AssertionError: {'part': 'snippet', 'playlistId': u'test-playlist-id', 'key': 'test-youtube-api- [truncated]... != {'part': 'snippet', 'playlistId': 'test-playlist-id', 'key': 'test-youtube-api-k [truncated]...
  {'key': 'test-youtube-api-key',
-  'maxResults': 50,
   'part': 'snippet',
-  'playlistId': u'test-playlist-id'}
?                -

+  'playlistId': 'test-playlist-id'}

**Comment by bendk** [comment]
That test should be fixed now.

**Comment by PCF-Testing** [comment]
Cannot run tests on the branch:

Traceback (most recent call last):
  File "/opt/apps/amara/manage.py", line 37, in <module>
    startup.startup()
  File "/opt/apps/amara/startup.py", line 68, in startup
    run_startup_modules()
  File "/opt/apps/amara/startup.py", line 58, in run_startup_modules
    __import__('%s.startup' % app)
  File "/opt/apps/amara/apps/teams/startup.py", line 21, in <module>
    import teams.workflows.startup
  File "/opt/apps/amara/apps/teams/workflows/startup.py", line 27, in <module>
    from teams.workflows.old import OldTeamWorkflow
  File "/opt/apps/amara/apps/teams/workflows/old/__init__.py", line 3, in <module>
    from .workflow import OldTeamWorkflow
  File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 26, in <module>
    from teams import views
  File "/opt/apps/amara/apps/teams/views.py", line 49, in <module>
    from teams.forms import (
  File "/opt/apps/amara/apps/teams/forms.py", line 135, in <module>
    class MoveTeamVideoForm(forms.Form):
  File "/opt/apps/amara/apps/teams/forms.py", line 138, in MoveTeamVideoForm
    team = forms.ModelChoiceField(queryset=Team.objects.all(),
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
    return self.get_query_set()
  File "/opt/apps/amara/apps/teams/models.py", line 129, in get_query_set
    return TeamQuerySet(Team).filter(deleted=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
    can_reuse=used_aliases, force_having=force_having)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
    process_extras=process_extras)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
    field, model, direct, m2m = opts.get_field_by_name(name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
    cache = self.init_name_map()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
    for f, model in self.get_all_related_m2m_objects_with_model():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
    cache = self._fill_related_many_to_many_cache()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
    for klass in get_models(only_installed=False):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/apps/amara/amara-enterprise/ondemand/models.py", line 8, in <module>
    from collab.models import Collaboration
  File "/opt/apps/amara/amara-enterprise/collab/models.py", line 60, in <module>
    class CollaborationSettings(models.Model):
  File "/opt/apps/amara/amara-enterprise/collab/models.py", line 85, in CollaborationSettings
    choices=get_subtitle_provider_choices())
  File "/opt/apps/amara/amara-enterprise/collab/models.py", line 50, in get_subtitle_provider_choices
    for value, provider_name in get_provider_choices():
  File "/opt/apps/amara/amara-enterprise/providers/types/__init__.py", line 40, in <genexpr>
    for choice in provider_type.get_choices()
  File "/opt/apps/amara/amara-enterprise/providers/types/queue.py", line 23, in get_choices
    for queue in ProviderQueue.objects.all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: no such table: providers_providerqueue

**Comment by PCF-Testing** [comment]
Please ignore the previous comment - the error was caused by a wrong commit on enterprise repo. The tests work well on the local instance.

**Comment by PCF-Testing** [comment]
Deployed.
