### ISSUE TITLE
Do not pre-populate email address when registering new users with FB/Twitter accounts

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2507]
Some users rush to confirm the dummy email address automatically appearing in the sign up dialog without stopping and reading the information on the purpose of the email address in the user account.

Expected: leave _Email address_ field blank and do not allow to proceed until it is filled with data, so that users take a moment to stop and consider their actions.

**Comment by syl22-00** [comment]
Done in branch gh-2507

**Comment by PCF-Testing** [comment]
The following tests are broken on the branch:

======================================================================
FAIL: test_all_permissions_pass (teams.tests.test_forms.VideoPageFormsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 289, in test_all_permissions_pass
    self.check_forms('edit', 'bulk-edit', 'move', 'remove')
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 286, in check_forms
    assert_items_equal(video_page_forms.enabled, correct_forms)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'add_form'

======================================================================
FAIL: test_cant_edit_video (teams.tests.test_forms.VideoPageFormsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 297, in test_cant_edit_video
    self.check_forms('move', 'remove')
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 286, in check_forms
    assert_items_equal(video_page_forms.enabled, correct_forms)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'add_form'

======================================================================
FAIL: test_cant_move_video (teams.tests.test_forms.VideoPageFormsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 301, in test_cant_move_video
    self.check_forms('edit', 'bulk-edit', 'remove')
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 286, in check_forms
    assert_items_equal(video_page_forms.enabled, correct_forms)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'add_form'

======================================================================
FAIL: test_cant_remove_video (teams.tests.test_forms.VideoPageFormsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 305, in test_cant_remove_video
    self.check_forms('edit', 'bulk-edit', 'move')
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 286, in check_forms
    assert_items_equal(video_page_forms.enabled, correct_forms)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'add_form'

**Comment by PCF-Testing** [comment]
Looks good on staging.

**Comment by PCF-Testing** [comment]
Deployed.
