### ISSUE TITLE
Record activity for move to/from a team

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2689]
We should create activity records for when a video gets moved to/from a team.  We should create 2 new activity types:

 - `video-moved-to-team` -- created when a video is moved to a team, either from another team or from the public area.
- `video-moved-from-team` --created when a video is moved from a team, either to another team or to the public area.

Here's the steps to implement a new activity type:
 - In activity/models.py, create a new ActivityType subclass.
   - The slug matches the names above.  Label should be something similar. 
   - I'm thinking related_model can be Team, and it will store the team that the video was moved from/to (or None in the case of a public video).
 - In activity/signalhandlers.py we should catch the signals that are emitted for these events and create the record.
   - I think we already have signalhandlers for all of these events, since we need to call `move_video_records_to_team()` to copy the records to the new team.
   - I'm thinking `private_to_team` should be true.  This makes it so the activity only appears on the team feed.  In addition to privacy concerns, this makes it so that one team doesn't see both the moved to and moved from records.
 - Write a unittest

**Comment by bendk** [comment]
@kslottow

**Comment by syl22-00** [comment]
Done in branch gh-2689

**Comment by PCF-Testing** [comment]
ValueError at /teams/team-tasks/activity/
incomplete format
Request Method:	GET
Request URL:	http://192.168.1.133:8000/en/teams/team-tasks/activity/
Django Version:	1.4.21
Exception Type:	ValueError
Exception Value:	
incomplete format
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/utils/functional.py in __mod__, line 142
Python Executable:	/usr/local/bin/uwsgi

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/teams/new_views.py" in wrapper
  90.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/amara/apps/teams/new_views.py" in activity
  736.         return render(request, template_dir + 'activity.html', context)
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py" in render
  44.     return HttpResponse(loader.render_to_string(*args, **kwargs),
File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
  176.         return t.render(context_instance)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  140.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  123.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  123.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  62.             result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  62.             result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  155.         return self.render_template(self.template, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render_template
  137.         output = template.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  140.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  282.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  186.                         nodelist.append(node.render(context))
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  155.         return self.render_template(self.template, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render_template
  137.         output = template.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  140.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render
  84.             output = self.filter_expression.resolve(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in resolve
  571.                 obj = self.var.resolve(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in resolve
  721.             value = self._resolve_lookup(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _resolve_lookup
  772.                             current = current()
File "/opt/apps/amara/apps/activity/models.py" in get_message
  598.         return self.type_obj.get_message(self)
File "/opt/apps/amara/apps/activity/models.py" in get_message
  296.         return self.format_message(record, msg, team=team.name)
File "/opt/apps/amara/apps/activity/models.py" in format_message
  61.         return msg % ActivityMessageDict(record, data)
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in __mod__
  142.                 return unicode(self) % rhs

Exception Type: ValueError at /teams/team-tasks/activity/
Exception Value: incomplete format

**Comment by syl22-00** [comment]
Sorry @PCF-Testing was a typo, pushed the fix

**Comment by PCF-Testing** [comment]
- [ ] Each entry should record the user who performed it - it's the whole point of logging moving videos. In the current version, the user does not get logged:

![movevideoactivityui](https://cloud.githubusercontent.com/assets/288455/20687268/ae74f164-b570-11e6-8b23-58eed30f1926.png)

![movevideoactivitybackend](https://cloud.githubusercontent.com/assets/288455/20687280/b8036300-b570-11e6-8a10-7eff638dfd0f.png)

- [ ] "Moved from" and "Moved to" activity records should appear both on origin and destination teams. They should be displayed or hidden based on the viewer's permissions:
* Public origin and destination teams should be visible to anyone
* If the team at the other end of the move is private, it should be shown only to the users who are members of that team and to superusers. Non-members without special permissions should not see where the video came from (or where it is moved)

- [ ] Activity entries displayed in the UI should include the link to the video. Example:
"[username @href=user_profile] moved video [video_title @href=video_url] from team [team_name @href=team_url]"

- [ ] "Activity Type" filter for all team types (old-style, collab, simple, customer, e-e) should include "Video moved to team" and "Video moved from team" values. They should correctly filter out activity values when applied.

**Comment by syl22-00** [comment]
So I finally implemented all those, including tests. Just about permission, right now the message displayed can not depend on the user who views the table, but as requested `private_to_team` is true.

**Comment by PCF-Testing** [comment]
Looks much better now. A few more comments though:

- [ ] When a video is added to a team without moving from another team (i.e. added directly or pulled from the public pool), "video added" entry should suffice. "moved [video] to [team] from non-team video" is not really needed in this case - especially given that this entry does not have the username of the doer.

- [ ] When a video is removed from a team into the public pool, could the activity entry say "[user] removed [video] from [team]" instead of "[user] moved [video] from [team] to non-team video"? The entries should still filter as "Video moved from team".

- [ ] This one is nice-have, not sure whether it is hard to do - when a video is permanently removed from the site (you can currently do that only with old-style teams), the activity entry about deletion only appears in the profile of the user who removed the video. Would it be possible to list it also in the team activity feed? This would be very helpful if we are serious about tracking video movement around the site.

- [ ] When a video is moved to/from another private team and the viewer is not a member of that other team, a click on the team name can produce a 404 page. This is not good usability- and security-wise. If there is no good way to change the output depending on who is viewing the activity feed (hiding links to private teams from non-members), maybe just remove the links to teams altogether? Amara staff should be able to find teams by name anyway.

**Comment by syl22-00** [comment]
I implemented and pushed all those. For the last item, I put it in a single separate commit so that we can easily take it in or out depending on @bendk feedback. It now includes code on amara-enterprise. 

The team where the video comes from or to is displayed according to permissions whether a user can see the teams notifications, which currently means team members and staff users.

One caveat for that item: on the admin pages, when listing all activity items, the message is currently displayed as for a user that does not have the permission (ie, it says "moved to/from another team").

**Comment by PCF-Testing** [comment]
The branch has exception on submitting a video to the public pool;

DatabaseError at /videos/create/
(1366, "Incorrect string value: '\\xF0\\x9F\\x87\\xB8\\xF0\\x9F...' for column 'text' at row 1")
Request Method:	POST
Request URL:	http://192.168.1.133:8000/en/videos/create/
Django Version:	1.4.21
Exception Type:	DatabaseError
Exception Value:	
(1366, "Incorrect string value: '\\xF0\\x9F\\x87\\xB8\\xF0\\x9F...' for column 'text' at row 1")

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/videos/views.py" in create
  203.     if video_form.is_valid():
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in is_valid
  124.         return self.is_bound and not bool(self.errors)
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _get_errors
  115.             self.full_clean()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in full_clean
  271.         self._clean_form()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _clean_form
  299.             self.cleaned_data = self.clean()
File "/opt/apps/amara/apps/videos/forms.py" in clean
  177.                 self.cleaned_data['video_url'], self.user)
File "/opt/apps/amara/apps/videos/models.py" in add
  711.             video.update_search_index()
File "/opt/apps/amara/apps/videos/models.py" in update_search_index
  436.         VideoIndex.index_video(self)
File "/opt/apps/amara/apps/videos/models.py" in index_video
  1215.                                                    defaults={'text': text})
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in get_or_create
  134.         return self.get_query_set().get_or_create(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in get_or_create
  452.                 obj.save(force_insert=True, using=self.db)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  463.         self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  551.                 result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in _insert
  203.         return insert_query(self.model, objs, fields, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in insert_query
  1593.     return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  912.             cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  40.             return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py" in execute
  114.             return self.cursor.execute(query, args)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: DatabaseError at /videos/create/
Exception Value: (1366, "Incorrect string value: '\\xF0\\x9F\\x87\\xB8\\xF0\\x9F...' for column 'text' at row 1")

Video: https://www.youtube.com/watch?v=jgj_TpQkUCc
The same video causes no problem when being submitted to the production server.

**Comment by syl22-00** [comment]
@PCF-Testing for the issue adding the video, see https://github.com/pculture/unisubs/issues/2699

**Comment by syl22-00** [comment]
@PCF-Testing I just pushed the fix for the second issue (broken user-level activity tab)

**Comment by PCF-Testing** [comment]
Looks really good now. Just a few minor things:

- [ ] Is it difficult to add activity record for the case when a video is added to team from a public pool, so that we could see who did that? This record could just say "[user] moved [video] to [current_team]".

- [ ] Is it intentional that in django admin for activity records videos have only titles displayed and no other identifier? Videos can be really hard to identify by title - consider, for example, LL videos or videos with URL for title. Could we also have video ID in admin pages?

- [ ] One unit test fails:
ERROR: test_video_moved_from_public_to_team (activity.tests.test_activity.TeamVideoActivityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/activity/tests/test_activity.py", line 325, in test_video_moved_from_public_to_team
    record_to = ActivityRecord.objects.get(type='video-moved-to-team')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 366, in get
    % self.model._meta.object_name)
DoesNotExist: ActivityRecord matching query does not exist.

**Comment by syl22-00** [comment]
@PCF-Testing I did those, but one thing is that even when a video is directly uploaded to a team, it is first added to the "public pool" then moved to the team. So we would always have two activity records: "video added" and "video moved to team".

**Comment by PCF-Testing** [comment]
I think two records should be fine.

For new teams, the activity record is missing the username. It says just: "moved [video] to [team]"

**Comment by syl22-00** [comment]
So this was actually an existing issue: most of the time, team videos did not have "added_by" field set, which is used in the activity record. I pushed changes so that we always keep track of who adds team videos.

**Comment by PCF-Testing** [comment]
Awesome! Making PRs for both repos.

**Comment by PCF-Testing** [comment]
Deployed.
