### ISSUE TITLE
Disconnecting YouTube channel from user account does not remove credits from video description

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2860]
Amara credits ("Help us caption & translate this video!") do not get removed from video descriptions when the channel is disconnected from Amara user account. They should.

Example: https://www.youtube.com/channel/UC2pr9bM8T-_BIWyfn2lyo7Q (both videos)

**Comment by PCF-Testing** [comment]
When fixing this, please ensure that if a description contains several entries of Amara credits (from multiple attempts to connect/disconnect the channel), they all get removed. Thanks!

**Comment by danantonioreyes** [comment]
Please test the fix I made in https://github.com/pculture/unisubs/tree/gh-enterprise-2860

**Comment by PCF-Testing** [comment]
Got the following exception on unlinking channel https://www.youtube.com/channel/UCdNveiSTYaqNP-nGiJtZbAw: 

APIError at /profiles/remove-third-party/youtube/11/
get_video_info: Unexpected content: list index out of range
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/profiles/remove-third-party/youtube/11/
Django Version:	1.7.11
Exception Type:	APIError
Exception Value:	
get_video_info: Unexpected content: list index out of range
Exception Location:	/opt/apps/amara/apps/externalsites/google.py in get_video_info, line 446

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/profiles/views.py" in remove_third_party
  384.             remove_credit_from_synced_youtube_videos(request.user)
File "/opt/apps/amara/apps/externalsites/credit.py" in remove_credit_from_synced_youtube_videos
  98.             remove_credit_to_video_url(video_url, account)
File "/opt/apps/amara/apps/externalsites/credit.py" in remove_credit_to_video_url
  78.         current_description = google.get_video_info(video_id).description
File "/opt/apps/amara/apps/externalsites/google.py" in get_video_info
  446.             raise e

Exception Type: APIError at /profiles/remove-third-party/youtube/11/
Exception Value: get_video_info: Unexpected content: list index out of range

**Comment by danantonioreyes** [comment]
@PCF-Testing  I've made some changes on how the video descriptions are cleaned, could you test again? I tested with my own youtube account with around 26 videos and a mix of public, private, and unlisted videos and things seem to work fine

**Comment by PCF-Testing** [comment]
Got the following exception trying to unlink a channel:

OAuthError at /profiles/remove-third-party/youtube/11/
Authentication error
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/profiles/remove-third-party/youtube/11/
Django Version:	1.7.11
Exception Type:	OAuthError
Exception Value:	
Authentication error
Exception Location:	/opt/apps/amara/apps/externalsites/google.py in _oauth_token_post, line 123

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/profiles/views.py" in remove_third_party
  383.         account.delete()
File "/opt/apps/amara/apps/externalsites/models.py" in delete
  709.         super(YouTubeAccount, self).delete()
File "/opt/apps/amara/apps/externalsites/models.py" in delete
  125.         super(ExternalAccount, self).delete()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in delete
  739.         collector.delete()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py" in delete
  257.                         sender=model, instance=obj, using=self.using
File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py" in send
  198.             response = receiver(signal=self, sender=sender, **named)
File "/opt/apps/amara/apps/externalsites/signalhandlers.py" in remove_credit_in_youtube_videos
  98.     access_token = google.get_new_access_token(instance.oauth_refresh_token)
File "/opt/apps/amara/apps/externalsites/google.py" in get_new_access_token
  178.                                  refresh_token=refresh_token)
File "/opt/apps/amara/apps/externalsites/google.py" in _oauth_token_post
  123.         raise OAuthError('Authentication error')

Exception Type: OAuthError at /profiles/remove-third-party/youtube/11/
Exception Value: Authentication error

I'd expect that channels can always be unlinked, even if their authentication data are outdated or corrupted, so that users had a chance to try and link anew after unlinking.

**Comment by PCF-Testing** [comment]
Still raising an exception, but this time it is a bit different:

UnboundLocalError at /profiles/remove-third-party/youtube/11/
local variable 'access_token' referenced before assignment
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/profiles/remove-third-party/youtube/11/
Django Version:	1.7.11
Exception Type:	UnboundLocalError
Exception Value:	
local variable 'access_token' referenced before assignment
Exception Location:	/opt/apps/amara/apps/externalsites/signalhandlers.py in remove_credit_in_youtube_videos, line 107
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/profiles/views.py" in remove_third_party
  382.         account.delete()
File "/opt/apps/amara/apps/externalsites/models.py" in delete
  709.         super(YouTubeAccount, self).delete()
File "/opt/apps/amara/apps/externalsites/models.py" in delete
  125.         super(ExternalAccount, self).delete()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in delete
  739.         collector.delete()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py" in delete
  257.                         sender=model, instance=obj, using=self.using
File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py" in send
  198.             response = receiver(signal=self, sender=sender, **named)
File "/opt/apps/amara/apps/externalsites/signalhandlers.py" in remove_credit_in_youtube_videos
  107.             tasks.remove_credit_to_video_url.delay(video_url, access_token)

Exception Type: UnboundLocalError at /profiles/remove-third-party/youtube/11/
Exception Value: local variable 'access_token' referenced before assignment

**Comment by danantonioreyes** [comment]
Added minor fix, also tested by corrupting the oauth token in the database--I hope that was a good replication of the issue you are encountering @PCF-Testing

**Comment by PCF-Testing** [comment]
The troublesome channel could be disconnected and reconnected again.

Now when unlinking this channel, I am seeing the following errors in the logs:
worker_1         | ERROR 2018-08-08 03:52:27,089 celery.worker.job Task externalsites.tasks.remove_credit_to_video_url[b561c756-31c1-45bf-81ed-cb169b237d68] raised exception: APIError('get_video_info: Unexpected content: list index out of range',)
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 233, in trace_task
worker_1         |     R = retval = fun(*args, **kwargs)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 420, in __protected_call__
worker_1         |     return self.run(*args, **kwargs)
worker_1         |   File "/opt/apps/amara/apps/externalsites/tasks.py", line 181, in remove_credit_to_video_url
worker_1         |     current_description = google.get_video_info(video_id).description
worker_1         |   File "/opt/apps/amara/apps/externalsites/google.py", line 446, in get_video_info
worker_1         |     raise e
worker_1         | APIError: get_video_info: Unexpected content: list index out of range
worker_1         | ERROR 2018-08-08 03:52:27,089 celery.worker.job Task externalsites.tasks.remove_credit_to_video_url[811128cd-4be8-4397-9e86-a73ae419ccd9] raised exception: APIError('get_video_info: Unexpected content: list index out of range',)
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 233, in trace_task
worker_1         |     R = retval = fun(*args, **kwargs)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 420, in __protected_call__
worker_1         |     return self.run(*args, **kwargs)
worker_1         |   File "/opt/apps/amara/apps/externalsites/tasks.py", line 181, in remove_credit_to_video_url
worker_1         |     current_description = google.get_video_info(video_id).description
worker_1         |   File "/opt/apps/amara/apps/externalsites/google.py", line 446, in get_video_info
worker_1         |     raise e
worker_1         | APIError: get_video_info: Unexpected content: list index out of range
worker_1         | ERROR 2018-08-08 03:52:27,090 celery.worker.job Task externalsites.tasks.remove_credit_to_video_url[55c58ae7-dd72-48f4-85a3-84227a532448] raised exception: APIError('get_video_info: Unexpected content: list index out of range',)
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 233, in trace_task
worker_1         |     R = retval = fun(*args, **kwargs)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 420, in __protected_call__
worker_1         |     return self.run(*args, **kwargs)
worker_1         |   File "/opt/apps/amara/apps/externalsites/tasks.py", line 181, in remove_credit_to_video_url
worker_1         |     current_description = google.get_video_info(video_id).description
worker_1         |   File "/opt/apps/amara/apps/externalsites/google.py", line 446, in get_video_info
worker_1         |     raise e
worker_1         | APIError: get_video_info: Unexpected content: list index out of range

**Comment by danantonioreyes** [comment]
Added code to catch the APIError being thrown out

**Comment by PCF-Testing** [comment]
Got intermittent results unlinking a channel with lots of videos; sent a copy of the log with errors to Dan.

**Comment by danantonioreyes** [comment]
Added a fix for removing description from private videos. 

Also I noticed that right now we don't add any credits to private videos, should we?

**Comment by PCF-Testing** [comment]
This time it has almost worked - Amara credits were cleaned on all but 3 oldest (and latest to get imported to the system) videos, out of 21.

>  right now we don't add any credits to private videos, should we?
I think this should be ok, private videos do not get auto-imported to the system, it is up to the channel owner if they want to add them manually.

**Comment by danantonioreyes** [comment]
Latest progress on this issue: removing the video credits fail when there are multiple videos to be processed (10+). I have tried with a synchronous implementation of `externalsites.signalhandlers.remove_credit_in_youtube_videos` but it still fails despite being similar to how `externalsites.credit.add_credit_to_video_url` is implemented
