### ISSUE TITLE
'EmptyQuerySet' object has no attribute 'for_url

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3049]
From newrelic (
https://rpm.newrelic.com/accounts/207361/applications/3323332/filterable_errors?tw%5Bdur%5D=last_30_minutes#/show/f02b66e5-de80-11e7-bab3-0242ac11000a_1918_4557/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&_k=v4f9mx)
```
Traceback (most recent call last):
File "/opt/apps/amara/deploy/unisubs.wsgi", line 74, in application
File "/usr/local/lib/python2.7/dist-packages/newrelic/api/web_transaction.py", line 1283, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python2.7/dist-packages/newrelic/api/web_transaction.py", line 810, in __init__
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 241, in __call__
File "/usr/local/lib/python2.7/dist-packages/newrelic/hooks/framework_django.py", line 434, in _nr_wrapper_BaseHandler_get_response_
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 192, in get_response
File "/usr/local/lib/python2.7/dist-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
File "/usr/local/lib/python2.7/dist-packages/newrelic/hooks/component_djangorestframework.py", line 46, in _nr_wrapper_APIView_dispatch_
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 464, in dispatch
File "/usr/local/lib/python2.7/dist-packages/newrelic/hooks/component_djangorestframework.py", line 53, in _handle_exception_wrapper
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 461, in dispatch
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 40, in list
File "/opt/apps/amara/apps/api/views/videos.py", line 608, in get_queryset
```

**Comment by bendk** [comment]
I'm going to fix this one in the gh-2137-stage2 branch.

**Comment by PCF-Testing** [comment]
@bendk: does this one need testing? If yes, what scenario could I use?

**Comment by bendk** [comment]
I think you can get with this URL path: `/api/videos/?team=non-existant-team&video_url=http://example.com/`

**Comment by bendk** [comment]
https://sentry.io/pculture/unisubs/issues/421511344/

**Comment by PCF-Testing** [comment]
Verified the fix on 2137-stage2.

**Comment by PCF-Testing** [comment]
Deployed.
