### ISSUE TITLE
Store activity record for video title change

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3150]
For #1831, we allowed admins the ability to edit video titles.  If they do that, we should create an activity record for this.

**Comment by bendk** [comment]
gh-3150

**Comment by PCF-Testing** [comment]
Logging works as expected. The two things missing are:

- [ ] New activity type in the team activity filter
- [ ] New activity type in the documentation (http://amara.readthedocs.io/en/latest/api.html#activity-types)

**Comment by bendk** [comment]
Just pushed a fix for both of those.

**Comment by PCF-Testing** [comment]
All the things related to activity look good. However, several unit tests that pass on dev fail on this branch:

======================================================================
ERROR: test_change_thumbnail (teams.tests.test_forms.TestEditVideosForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/utils/test_utils/monkeypatch.py", line 246, in wrapper
    return func(self, mock_obj, *args, **kwargs)
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 81, in test_change_thumbnail
    'thumbnail': mock_file,
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 53, in build_form
    form.submit()
  File "/opt/apps/amara/apps/ui/forms/forms.py", line 134, in submit
    self.perform_submit(self.iter_objects(progress_callback))
  File "/opt/apps/amara/apps/teams/forms.py", line 1992, in perform_submit
    video.update_title(self.user, self.cleaned_data['title'])
KeyError: 'title'

======================================================================
ERROR: test_no_changes (teams.tests.test_forms.TestEditVideosForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 100, in test_no_changes
    'language': '',
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 53, in build_form
    form.submit()
  File "/opt/apps/amara/apps/ui/forms/forms.py", line 134, in submit
    self.perform_submit(self.iter_objects(progress_callback))
  File "/opt/apps/amara/apps/teams/forms.py", line 1992, in perform_submit
    video.update_title(self.user, self.cleaned_data['title'])
KeyError: 'title'

======================================================================
ERROR: test_set_language (teams.tests.test_forms.TestEditVideosForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 91, in test_set_language
    'language': 'en',
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 53, in build_form
    form.submit()
  File "/opt/apps/amara/apps/ui/forms/forms.py", line 134, in submit
    self.perform_submit(self.iter_objects(progress_callback))
  File "/opt/apps/amara/apps/teams/forms.py", line 1992, in perform_submit
    video.update_title(self.user, self.cleaned_data['title'])
KeyError: 'title'

======================================================================
ERROR: test_set_project (teams.tests.test_forms.TestEditVideosForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 60, in test_set_project
    'project': self.project.id,
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 53, in build_form
    form.submit()
  File "/opt/apps/amara/apps/ui/forms/forms.py", line 134, in submit
    self.perform_submit(self.iter_objects(progress_callback))
  File "/opt/apps/amara/apps/teams/forms.py", line 1992, in perform_submit
    video.update_title(self.user, self.cleaned_data['title'])
KeyError: 'title'

======================================================================
ERROR: test_unset_project (teams.tests.test_forms.TestEditVideosForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 69, in test_unset_project
    'project': self.team.default_project.id,
  File "/opt/apps/amara/apps/teams/tests/test_forms.py", line 53, in build_form
    form.submit()
  File "/opt/apps/amara/apps/ui/forms/forms.py", line 134, in submit
    self.perform_submit(self.iter_objects(progress_callback))
  File "/opt/apps/amara/apps/teams/forms.py", line 1992, in perform_submit
    video.update_title(self.user, self.cleaned_data['title'])
KeyError: 'title'

======================================================================
FAIL: test_public_vimeo_url (providers.tests.test_providers.ProviderRequestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/amara-enterprise/providers/tests/test_providers.py", line 62, in test_public_vimeo_url
    assert(re.match(VIMEO_REGEXP, self.request.video_file_url()))
AssertionError

**Comment by bendk** [comment]
Fixed the unittests.  I'm going to make a PR for this one now, tell me if I should have waited for more testing first.

**Comment by PCF-Testing** [comment]
These activity records are borked on staging:

![screenshot from 2018-04-19 03 57 37](https://user-images.githubusercontent.com/288455/38987834-020644b4-4386-11e8-8fcd-e7f7f543dd09.png)

![screenshot from 2018-04-19 03 58 06](https://user-images.githubusercontent.com/288455/38987840-07912f8e-4386-11e8-83c5-66726b6fa8cc.png)

https://staging.amara.org/en/teams/m-collab-test/activity/

**Comment by PCF-Testing** [comment]
Seeing the following exception on staging branch locally:

ValueError at /teams/collab-test/activity/
Single '}' encountered in format string
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/collab-test/activity/
Django Version:	1.7.11
Exception Type:	ValueError
Exception Value:	
Single '}' encountered in format string
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/utils/functional.py in __wrapper__, line 135

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/teams/new_views.py" in wrapper
  95.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/amara/apps/teams/new_views.py" in activity
  713.         return render(request, template_dir + 'activity.html', context)
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py" in render
  50.     return HttpResponse(loader.render_to_string(*args, **kwargs),
File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
  178.         return t.render(context_instance)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  150.                 return template.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  312.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  201.                             nodelist.append(node.render(context))
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  312.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  150.                 return template.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render
  90.             output = self.filter_expression.resolve(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in resolve
  624.                 new_obj = func(obj, *arg_vals)
File "/opt/apps/amara/apps/activity/templatetags/activity_tags.py" in get_old_record_message
  29.     return record.get_old_message(user)
File "/opt/apps/amara/apps/activity/models.py" in get_old_message
  1030.         return self.type_obj.get_old_message(self, user)
File "/opt/apps/amara/apps/activity/models.py" in get_old_message
  225.             video=record.get_video_title())
File "/usr/local/lib/python2.7/dist-packages/django/utils/html.py" in format_html
  94.     return mark_safe(format_string.format(*args_safe, **kwargs_safe))
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in __wrapper__
  135.                         return self.__dispatch[t][funcname](res, *args, **kw)

Exception Type: ValueError at /teams/collab-test/activity/
Exception Value: Single '}' encountered in format string

**Comment by bendk** [comment]
I think this is fixed on staging now

**Comment by PCF-Testing** [comment]
Confirming it is fixed.

**Comment by PCF-Testing** [comment]
Deployed.
