### ISSUE TITLE
Exception(Standard 'bcp47' is not registred)

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#477]
I get this error when I attempt to add this youtube video to amara:

https://www.youtube.com/watch?v=jqxENMKaeCU

ERROR 2013-06-07 16:03:18,209 tasks 19581 140427050026752 Celery job exception: 
Traceback (most recent call last):
  File "/opt/ve/vagrant/unisubs/lib/python2.6/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/opt/apps/vagrant/unisubs/apps/videos/types/youtube.py", line 224, in save_subtitles_for_lang
    lc  = LanguageCode(yt_lc, "bcp47").encode("unisubs")
  File "/opt/apps/vagrant/unisubs/libs/unilangs/unilangs.py", line 1068, in **init**
Exception: Standard 'bcp47' is not registred

**Comment by bendk** [comment]
Pretty sure this one got fixed along the way somewhere.
